### ISSUE TITLE
about Rosetta.ref('tabs2')

### ISSUE THREAD

**Issue by costlife** [jiexuangao/rosetta#2]
when I use a function supported by an element like
```
tabs2.switchTo(1)
```
I have to type the code first
```
var tabs2 = Rosetta.ref('tabs2');
``` 
but there comes a problem as below
```
var tabs2 = Rosetta.ref('tabs2');
tabs2.switchTo(1);
tabs2.switchTo(0);
```
3rd line 'tabs2.switchTo(0)' doesn't work, but if I use 
```
var tabs2 = Rosetta.ref('tabs2');
tabs2.switchTo(1);
var tabs2 = Rosetta.ref('tabs2');
tabs2.switchTo(0);
```
it works again. 
is there a good solution for this question?

**Comment by jiexuangao** [comment]
fixed~
